[versions]
junit = "4.13.2"
androidXJunit = "1.3.0"
elimuContentProvider = "1.4.66"

androidXEspresso = "3.7.0"
agp = "8.8.2"
kotlin = "2.3.10"
coreKtx = "1.16.0"

[libraries]
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidXEspresso" }
agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
elimu-content-provider = { group = "ai.elimu", name = "content-provider", version.ref = "elimuContentProvider" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXJunit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }